# Generated by Django 4.2.1 on 2023-05-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
